#!/usr/bin/env bash
set -Eeu
set -o posix
set -o pipefail

declare -r bitcoin_log="/vagrant/guest_logs/bitcoin.log"

declare -r exe_name="$0"
echo_log() {
    local log_target="$bitcoin_log"
    echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')] $exe_name: $@" >> $log_target
}

function error {
    echo "$1" 1>&2
    exit 1
}

set -x
echo_log "starting bitcoind"
~/bitcoind
echo "Sleeping a while to let bitcoind get going..."
sleep 5
