#!/usr/bin/env bash

if ! pgrep bitcoind > /dev/null 2>&1
  then echo -en '\e[31m[not running]\e[00m'
else
  bitcoin-cli help > /dev/null 2>&1
  RUNNING=$?
  if (($RUNNING == 28))
    then echo -en '\e[31m[starting]\e[00m'
  elif (($RUNNING == 0))
    then CHAIN=$(bitcoin-cli getblockchaininfo 2>/dev/null | grep "\"chain\"" | cut -f 4 -d "\"")
    if [ "$CHAIN" == 'test' ]
      then echo -en '\e[34m[\e[01;34mtestnet\e[00;34m]\e[00m'
    elif [ "$CHAIN" == 'main' ]
      then echo -en '\e[32m[\e[01;32mmainnet\e[00;32m]\e[00m'
    elif [ "$CHAIN" == 'regtest' ]
      then echo -en '\e[33m[\e[01;33mregtest\e[00;33m]\e[00m'
    fi
  else
    echo -en '\e[31m[not running]\e[00m'
  fi
fi
