#!/usr/bin/env bash

usage="$(basename "$0") [-s] [-g] - build bitcoin from source

where:
    -h show this (h)elp text
    -x run the extended python test cases"

function error
{
    echo "$1" 1>&2
    exit 1
}

coin=''
while getopts 'x' flag; do
  case "${flag}" in
    h) echo "$usage"
       exit
       ;;
    x) extended="extended" ;;
    *) error "Unexpected option" ;;
  esac
done

test_bitcoin

if [ "$extended" = true ]; then
  ~/bitcoin/qa/pull-tester/rpc-tests.py -extended
else
  ~/bitcoin/qa/pull-tester/rpc-tests.py
fi